/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Testrep;

public class App {
    public String getGreeting() {
        return "Hello from MANVITHA/DEV." + "More changes from my branch"; 
		
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
